### ISSUE TITLE
No implementation found for method connectToWifi on channel wifi_connector

### ISSUE THREAD

**Issue by bahador-r** [wonjerry/flutter_wifi_connector#2]
when i try to connect to wifi , i see this error:
```
E/flutter (15218): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method connectToWifi on channel wifi_connector)
E/flutter (15218): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (15218): <asynchronous suspension>
E/flutter (15218): #1      WifiConnector.connectToWifi (package:wifi_connector/wifi_connector.dart:10:12)
E/flutter (15218): <asynchronous suspension>
E/flutter (15218): #2      _InternetPageState.storeAndConnectWiFi
package:machine/…/setup/internetPage.dart:72
E/flutter (15218): <asynchronous suspension>
E/flutter (15218):
```

**Comment by vanlooverenkoen** [comment]
I will close this ticket. If you are still having issues with this comment on this ticket and we will reopen it.

**Comment by rimedar** [comment]
`E/flutter ( 7198): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method connectToWifi on channel wifi_connector)`

version wifi_connector 1.0.2, in android

**Comment by gittogeorgeevelabs** [comment]
when i try to connect to wifi , i see this error:

E/flutter (15218): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method connectToWifi on channel wifi_connector)
E/flutter (15218): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (15218): <asynchronous suspension>
E/flutter (15218): #1      WifiConnector.connectToWifi (package:wifi_connector/wifi_connector.dart:10:12)
E/flutter (15218): <asynchronous suspension>
E/flutter (15218): #2      _InternetPageState.storeAndConnectWiFi
package:machine/…/setup/internetPage.dart:72
E/flutter (15218): <asynchronous suspension>
E/flutter (15218):   
i also facing same issue its showing error like this, is there any solution for this
