### ISSUE TITLE
wifi_connector Android 11

### ISSUE THREAD

**Issue by sokunsamnang** [wonjerry/flutter_wifi_connector#3]
Did WifiConnector.connectToWifi() will work well on android 11??

**Comment by vanlooverenkoen** [comment]
It was not working for me after fixing #5 it did work.

**Comment by vanlooverenkoen** [comment]
for now it will not. I created separate tickets for suggestion API's & peer to peer connect API's

#19 
#20 

You can follow the progress for each implementation with these tickets
